apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-green-config
  namespace: production
data:
  MODEL_VERSION: "2"
  MODEL_SHA256: "b8f844236936a3c0e0d676bba9b97c82f24e505ab9cb5c5217fa162da5e59484"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-green
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference-green
      environment: production
  template:
    metadata:
      labels:
        app: inference-green
        environment: production
        app.kubernetes.io/name: inference
        slot: green
    spec:
      containers:
        - name: inference
          image: 616150220350.dkr.ecr.eu-central-1.amazonaws.com/final-inference@sha256:aa48b9c99efa015c4ee5e77212b0a37fc9df62ed5668de433ec2e02bbeefd94f
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: inference-green-config
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
