{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Application",
  "metadata": {
    "name": "final-rbac",
    "namespace": "mlops-system",
    "finalizers": [
      "resources-finalizer.argocd.argoproj.io"
    ]
  },
  "spec": {
    "project": "default",
    "source": {
      "repoURL": "https://github.com/anastasiia-p-807/MLOps_full_deployment.git",
      "targetRevision": "HEAD",
      "path": "rbac"
    },
    "destination": {
      "server": "https://kubernetes.default.svc",
      "namespace": "staging"
    },
    "syncPolicy": {
      "automated": {
        "prune": true,
        "selfHeal": true
      },
      "syncOptions": [
        "CreateNamespace=true"
      ]
    }
  }
}
